### ISSUE TITLE
Cannot set sequence. Illegal character in string

### ISSUE THREAD

**Issue by josecarballo87** [dmnfarrell/smallrnaseq#11]
Dear Damien,
I am running smallrnaseq and I got this message in the novel module of the pipeline.
```
predicting novel mirnas..
pooled 6 files into 2162077 unique reads
getting default classifier
finding read clusters
128485 read clusters in 1161901 reads
3031 clusters above reads cutoff
Cannot set sequence. Illegal character in string 'CUAAGAACACUACCCCACUUAAAAUGAUUUUAACUCCUUCACAUCCAAAACGGCAUUUCAUGGUGGCU5'
Cannot set sequence. Illegal character in string 'CUAAGAACACUACCCCACUUAAAAUGAUUUUAACUCCUUCACAUCCAAAACGGCAUUUCAUGGUGGCU559_'
Cannot set sequence. Illegal character in string 'CUAAGAACACUACCCCACUUAAAAUGAUUUUAACUCCUUCACAUCCAAAACGGCAUUUCAUGGUGGCU559_eno'
Cannot set sequence. Illegal character in string 'CUAAGAACACUACCCCACUUAAAAUGAUUUUAACUCCUUCACAUCCAAAACGGCAUUUCAUGGUGGCU559_enobkg'
Cannot set sequence. Illegal character in string 'CUAAGAACACUACCCCACUUAAAAUGAUUUUAACUCCUUCACAUCCAAAACGGCAUUUCAUGGUGGCU559_enobkgtB>'
Cannot set sequence. Illegal character in string 'CUAAGAACACUACCCCACUUAAAAUGAUUUUAACUCCUUCACAUCCAAAACGGCAUUUCAUGGUGGCU559_enobkgtB>AG'
Cannot set sequence. Illegal character in string 'CUAAGAACACUACCCCACUUAAAAUGAUUUUAACUCCUUCACAUCCAAAACGGCAUUUCAUGGUGGCU559_enobkgtB>AGUGG'
Cannot set sequence. Illegal character in string 'CUAAGAACACUACCCCACUUAAAAUGAUUUUAACUCCUUCACAUCCAAAACGGCAUUUCAUGGUGGCU559_enobkgtB>AGUGGCGU'
Cannot set sequence. Illegal character in string 'CUAAGAACACUACCCCACUUAAAAUGAUUUUAACUCCUUCACAUCCAAAACGGCAUUUCAUGGUGGCU559_enobkgtB>AGUGGCGUGCA'
Cannot set sequence. Illegal character in string 'CUCUG>Backbone_7077CCAAGCUGAAGUAUUGGCGCACUCACGGUG'
Cannot set sequence. Illegal character in string 'UUGCUCUG>Backbone_7077CCAAGCUGAAGUAUUGGCGCACUCACGGUG'
Cannot set sequence. Illegal character in string 'UUUUUGCUCUG>Backbone_7077CCAAGCUGAAGUAUUGGCGCACUCACGGUG'
Cannot set sequence. Illegal character in string 'ACUUUUUUGCUCUG>Backbone_7077CCAAGCUGAAGUAUUGGCGCACUCACGGUG'
Cannot set sequence. Illegal character in string 'AGCACUUUUUUGCUCUG>Backbone_7077CCAAGCUGAAGUAUUGGCGCACUCACGGUG'
Cannot set sequence. Illegal character in string 'UUCAGCACUUUUUUGCUCUG>Backbone_7077CCAAGCUGAAGUAUUGGCGCACUCACGGUG'
Cannot set sequence. Illegal character in string 'UUUUUCAGCACUUUUUUGCUCUG>Backbone_7077CCAAGCUGAAGUAUUGGCGCACUCACGGUG'
Cannot set sequence. Illegal character in string 'UUCUUUUUCAGCACUUUUUUGCUCUG>Backbone_7077CCAAGCUGAAGUAUUGGCGCACUCACGGUG'
Cannot set sequence. Illegal character in string 'CCAUUCUUUUUCAGCACUUUUUUGCUCUG>Backbone_7077CCAAGCUGAAGUAUUGGCGCACUCACGGUG'
Cannot set sequence. Illegal character in string 'AUUCCAUUCUUUUUCAGCACUUUUUUGCUCUG>Backbone_7077CCAAGCUGAAGUAUUGGCGCACUCACGGUG'
Cannot set sequence. Illegal character in string 'AUGAUUCCAUUCUUUUUCAGCACUUUUUUGCUCUG>Backbone_7077CCAAGCUGAAGUAUUGGCGCACUCACGGUG'
Cannot set sequence. Illegal character in string 'CGAAUGAUUCCAUUCUUUUUCAGCACUUUUUUGCUCUG>Backbone_7077CCAAGCUGAAGUAUUGGCGCACUCACGGUG'
took 3173.892 seconds
no precursors found above cutoff
Could not find any novel mirnas.
There may not be sufficient aligned reads or the score cutoff is too high.` 
```
Seems that the name of the conting which is Backbone_XXX is attached to the sequence.
I am not sure, but maybe is a formatting problem or something like that. 
Any idea what I can do to solve this issue?
```

**Comment by zero555666** [comment]
Dear Damien,
I am running smallrnaseq and I got error message in app.py,could you help me!!
Traceback (most recent call last):
  File "/home/zhangjun/miniconda3/bin/smallrnaseq", line 8, in <module>
    sys.exit(main())
  File "/home/zhangjun/miniconda3/lib/python3.7/site-packages/smallrnaseq/app.py", line 543, in main
    W.run()
  File "/home/zhangjun/miniconda3/lib/python3.7/site-packages/smallrnaseq/app.py", line 124, in run
    self.map_libraries()
  File "/home/zhangjun/miniconda3/lib/python3.7/site-packages/smallrnaseq/app.py", line 179, in map_libraries
    plot_results(res, out)
TypeError: plot_results() missing 1 required positional argument: 'path'
