### ISSUE TITLE
dict object has no attribute 'has key'

### ISSUE THREAD

**Issue by patrickeboada** [dmnfarrell/smallrnaseq#13]
Hi Damien, 

I really appreciate your small rna seq workflow. I am trying to test it for a paired small rna set to bulk rna set.

I am running into an error when I initialize the program as per your YouTube video / tutorial webpage

(RNAseqSTAR) patrickboada@patrickboada smallrna %  smallrnaseq -c default.conf 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/smallrnaseq", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/smallrnaseq/app.py", line 560, in main
    config.write_default_config(conffile, defaults=config.baseoptions)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/smallrnaseq/config.py", line 60, in write_default_config
    cp = create_config_parser_from_dict(defaults, ['base','novel','aligner','de'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/smallrnaseq/config.py", line 71, in create_config_parser_from_dict
    if not data.has_key(s):
AttributeError: 'dict' object has no attribute 'has_key'

Have you run into this error before?

Best,
Patrick

**Comment by dmnfarrell** [comment]
I think Python 3 doesn't support has_key now. I've updated it but not tested the change. You'd have to update via github.
