### ISSUE TITLE
Error saving de_genes_edger.csv

### ISSUE THREAD

**Issue by sateeshperi** [dmnfarrell/smallrnaseq#2]
```
Rscript /home/sateeshp/.local/lib/python2.7/site-packages/smallrnaseq/DEanalysis.R de_counts.csv
Loading required package: limma

Traceback (most recent call last):
  File "/home/sateeshp/.local/bin/smallrnaseq", line 11, in <module>
    sys.exit(main())
  File "/home/sateeshp/.local/lib/python2.7/site-packages/smallrnaseq/app.py", line 484, in main
    diff_expression(options)
  File "/home/sateeshp/.local/lib/python2.7/site-packages/smallrnaseq/app.py", line 363, in diff_expression
    res.to_csv(os.path.join(path,'de_genes_edger.csv'), float_format='%.4g')
  File "/home/sateeshp/.local/lib/python2.7/site-packages/pandas/core/frame.py", line 1745, in to_csv
    formatter.save()
  File "/home/sateeshp/.local/lib/python2.7/site-packages/pandas/io/formats/csvs.py", line 156, in save
    compression=self.compression)
  File "/home/sateeshp/.local/lib/python2.7/site-packages/pandas/io/common.py", line 397, in _get_handle
    f = open(path_or_buf, mode)
IOError: [Errno 2] No such file or directory: 'results2/de_genes_edger.csv'
```
Could this be a float_format save option error ?

I would be happy to share the entire log if you need. do let me know. Thank you

**Comment by dmnfarrell** [comment]
does the folder results2 exist?

**Comment by sateeshperi** [comment]
yes....results2 exists and I get the edgeR_output file which stops after that!

**Comment by sateeshperi** [comment]
you were right! I was executing from within the results2 folder. My bad! Thanks for catching that
