### ISSUE TITLE
Error in collapsing the file

### ISSUE THREAD

**Issue by offenspergerfelix** [dmnfarrell/smallrnaseq#5]
No matter in which format I create the input file (fastq,fasta) for the config file, I always get the same error message about a missing file that should be created from your script. Even if the collapsing step wouldn't even be necessary anymore..
```
collapsing reads **.fa

Traceback (most recent call last):
  File "/home/.local/bin/smallrnaseq", line 11, in <module>
    load_entry_point('smallrnaseq==0.5.0', 'console_scripts', 'smallrnaseq')()
  File "/home/.local/lib/python2.7/site-packages/smallrnaseq/app.py", line 504, in main
    W.run()
  File "/home/.local/lib/python2.7/site-packages/smallrnaseq/app.py", line 105, in run
    self.map_genomic_features()
  File "/home/.local/lib/python2.7/site-packages/smallrnaseq/app.py", line 264, in map_genomic_features
    aligner_params=params)
  File "/home/.local/lib/python2.7/site-packages/smallrnaseq/base.py", line 411, in map_genome_features
    cfiles = collapse_files(files, outpath)
  File "/home/.local/lib/python2.7/site-packages/smallrnaseq/base.py", line 529, in collapse_files
    res = collapse_reads(f, outfile=collapsedfile, kwargs)
  File "/home/.local/lib/python2.7/site-packages/smallrnaseq/base.py", line 514, in collapse_reads
    utils.dataframe_to_fasta(df, idkey='read_id', outfile=outfile)
  File "/home/.local/lib/python2.7/site-packages/smallrnaseq/utils.py", line 198, in dataframe_to_fasta
    fastafile = open(outfile, "w")
IOError: [Errno 2] No such file or directory: 'results/temp/**.fa
```

The directory results is is existend, but not temp after the error occured.

**Comment by dmnfarrell** [comment]
I'd have to see the config file. Are you providing wildcards for inputs like **.fa? That won't work.
